(defun cilindro () 
    (print "Estamos calculando el volumen de un cilindro, dame la medida del radio: ") 
    (setq a (read)) 
    (print "Dame la medida de la altura: ") 
    (setq b (read)) ( * ( * ( * a a ) b ) 3.1416 ) 
)