(defun prismaTriangular () 
    (print "Estamos calculando el volumen de un prisma triangular, dame la medida de la base: ") 
    (setq a (read)) 
    (print "Dame la medida de la altura de un lado: ") 
    (setq b (read)) 
    (print "Dame la medida de la altura del prisma: ") 
    (setq c (read)) ( * ( / ( * a b ) 2 ) c ) 
)