(defun prismaPiramidal () 
    (print "Estamos calculando el volumen de un prisma piramidal, dame la medida de un lado de la base: ") 
    (setq a (read)) 
    (print "Dame la medida de la altura : ") 
    (setq b (read)) ( / ( * ( * a a ) b ) 3) 
)