(defun prismaPentagonal () 
    (print "Estamos calculando el volumen de un prisma pentagonal, dame la medida de un lado: ") 
    (setq a (read)) 
    (print "Dame la medida del apotema: ") 
    (setq b (read)) 
    (print "Dame la medida de la altura: ") 
    (setq c (read)) ( * (* ( * a 5 )( + b c )) c ) 
)